export const siteConfig = {
  name: "Yashwant Gawande - Full Stack Developer Portfolio",
  url: "https://www.yashwantgawande.com" /*url of the site after deployment*/,
  ogImage: "https://www.yashwantgawande.com/og.png",
  description:
    "Yashwant Gawande, Full Stack Developer skilled in Next.js, React, Node.js, and TypeScript. Expertise in building scalable systems, intuitive UI/UX, cloud services (AWS, Docker), and modern databases like PostgreSQL and MongoDB.",
  seoKeywords: [
    "Yashwant Gawande",
    "Yashwant Gawande Full Stack Developer",
    "Full Stack Developer Portfolio Yashwant Gawande",
    "Yashwant Gawande React Developer",
    "Full Stack Developer",
    "Full Stack Web Developer",
    "Web Developer Portfolio",
    "Next.js Developer",
    "React Developer",
    "Node.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "React.js Portfolio",
    "Modern Web Development",
    "Full Stack Developer in [Your Location]",
    "Next.js Expert",
    "React.js Expert",
    "Node.js Expert",
    "PostgreSQL Developer",
    "MongoDB Developer",
    "Tailwind CSS Developer",
    "GraphQL Developer",
    "REST API Development",
    "Web Application Development",
    "Scalable Web Systems",
    "Full Stack Developer Portfolio for Next.js and React",
    "Hire Full Stack Developer for Scalable Web Applications",
    "Full Stack Developer with PostgreSQL and MongoDB expertise",
    "JavaScript Full Stack Developer Portfolio",
    "Experienced Full Stack Developer for modern web apps",
    "Portfolio of Yashwant Gawande - Full Stack Developer",
    "Expert Next.js React Developer for Hire",
    "Building scalable systems with Next.js and Node.js",
    "Building modern web applications using TypeScript and React",
  ],
  links: {
    twitter: "https://twitter.com/yashng7",
    github: "https://github.com/yashng7/portfolio-new",
  },
};

export type SiteConfig = typeof siteConfig;
